const bestSaller = [
  {
    id: 134,
    name: "Vở kẻ ngang chấm B5 200tr Klong",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220901_tr4Gdm3QstNcQo6iO0Axiu2F.jpg",
    price: "32,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 135,
    name: "Vở kẻ ngang chấm B5 120tr Klong",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220901_NJC1DvBGqd5UDtt4wE2ffutj.jpg",
    price: "20,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 136,
    name: "Sticker chữ ánh bạc cổ điển STI57",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220511_BGmTBSS993CYuBSvyIUfmNAi.png",
    price: "7,500",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 137,
    name: "Kệ giỏ nhựa mini K37",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20211125_w196Z2qa7Yz6s3KseAVjalTb.jpg",
    price: "54,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 138,
    name: "Sổ còng caro bìa nhựa A5 100 tờ",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210621_zkM2XD6Yft9TI90cJS1O2kB0.jpeg",
    price: "49,470",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 139,
    name: "Vở kẻ ngang chấm B5 100tr Klong",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220901_tr4Gdm3QstNcQo6iO0Axiu2F.jpg",
    price: "15,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
];
