const hotProduct = [
  {
    id: 128,
    name: "Vở Dash Line lò xo kép bìa nhựa B5 200 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240424_DkfC0x3cDk.jpeg",
    price: "36,800",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 129,
    name: "Vở Dash Line lò xo kép bìa nhựa B5 120 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240424_DkfC0x3cDk.jpeg",
    price: "26,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 130,
    name: "Vở Dash Line lò xo kép bìa nhựa A5 200 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240424_DkfC0x3cDk.jpeg",
    price: "30,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 131,
    name: "Vở Dash Line lò xo kép bìa nhựa A5 120 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240424_DkfC0x3cDk.jpeg",
    price: "22,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 132,
    name: "Vở Dash Line lò xo kép bìa nhựa C5 200 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240424_DkfC0x3cDk.jpeg",
    price: "28,860",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 133,
    name: "Vở Dash Line lò xo kép bìa nhựa C5 120 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240424_DkfC0x3cDk.jpeg",
    price: "22,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
];
