const pen = [
  {
    id: 110,
    name: "Bút bi ge 3 ngòi bấm màu cổ điển B106",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20231225_QlxAgsedAi.png",
    price: "19,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 111,
    name: "Bút bi đệm tay lớn chống mỏi quả đào B104",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20231114_sj0DHJXWk2.png",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 112,
    name: "Bút bi đệm tay êm hình đại dương B102",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_gZMhyAI9Ni.jpeg",
    price: "15,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 113,
    name: "Bút bi mực đen Mura cài kim loại trắng B97",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_At0I6JTvim.jpeg",
    price: "14,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 114,
    name: "Ruột bút mực đỏ B88R",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20231129_JEyLDYS8lg.jpeg",
    price: "6,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 115,
    name: "Ruột bút mực xanh B88R",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20231129_jQTK8c5bbo.jpeg",
    price: "6,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 116,
    name: "Bộ 6 bút bi bấm Resun mực đen style hiện đại",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_aCaaCVddOU.jpeg",
    price: "89,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 117,
    name: "Bút bi mực gel phong cách Nhật Bản B65",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_NsZ16V1AQs.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 118,
    name: "Bút bi đệm tay lớn chống mỏi Simple life B93",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_iOatYeJpGb.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 119,
    name: "Bút bi bấm Thỏ hồng cài kim loại B90",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_JMgGDNtKeE.jpeg",
    price: "14,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 120,
    name: "Bộ 5 bút bi màu pastel B87 Rosy Posy",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_7BbokY3iks.jpeg",
    price: "68,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 121,
    name: "Bút bi Lopet cài kim loại trà xanh B86",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_rSeaIdZRQe.jpeg",
    price: "14,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
];
