const penColor = [
  {
    id: 122,
    name: "Bút lông màu Monami B46",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220511_fn74OwvmFAmSZ6vU9mGDgqwI.jpg",
    price: "7,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 123,
    name: "Bút sáp bộ 10 màu Thiên Long Colokit Doraemon",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_QWO26cSiG3ZYipj9tY40tGSg.jpg",
    price: "16,500",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 124,
    name: "Bút sáp bộ 16 màu Thiên Long Colokit Doraemon",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_2Q1LfvLNj2yDxAQJqEgBiIP8.jpg",
    price: "23,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 125,
    name: "Màu nước bộ 8 màu kèm cọ tô Thiên Long",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_5eGqw84HHk1PddAI9EjQh2ar.jpg",
    price: "22,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 126,
    name: "Bút sáp tô màu 24 màu Thiên Long",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_Z5f5Jzhalzd96TFfQBC3ICZ1.jpg",
    price: "31,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 127,
    name: "Sáp 12 màu Thiên Long Colokit CR-C016",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_WGcjLiebLThfswCNFEv8FojA.jpg",
    price: "8,800",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
];
