const penDifferent = [
  {
    id: 60,
    name: "Bút xóa băng kéo linh hoạt dang bấm B103",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_nco1rEyLFy.jpeg",
    price: "22,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 61,
    name: "Bút ngòi kim mực nước B49",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220705_SIxVbn1WxVglE881cpC1hoDS.jpg",
    price: "4,500",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 62,
    name: "Bút Marker kèm đi nét 2 đầu B44 Aihao 3191",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220416_7JUX6Y6r9O3w5Md1a8TNxG27.png",
    price: "6,500",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 63,
    name: "Bút xóa Thiên Long CP-05",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_dJWmtVCyUKVtfvcWZ9yFNoT2.jpg",
    price: "17,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 64,
    name: "Bút xóa Thiên Long CP-02",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220311_9gzbUh81vZjCx2R97oLkIfws.jpg",
    price: "22,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },

  {
    id: 65,
    name: "Bộ 2 bút xóa kéo mini B26",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210908_ROF5MIbmMxz3pkHV3HLtVC3L.jpg",
    price: "16,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 66,
    name: "Combo bút Baoke + hộp mực B16",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210709_VpJserhpU7rOSZcdwtddyVnf.jpg",
    price: "22,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 67,
    name: "Bút viết calligraphy Bao ke B15",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210709_CYXrYVmCE6grq5WT37aiAeRD.jpg",
    price: "18,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 68,
    name: "Bút sơn acrylic STA1000 B13",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210628_rO9dPaZq9vugLtse04nRGDAB.jpg",
    price: "19,900",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 69,
    name: "Bút xóa kéo 2 đầu chân mèo",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210621_aj6SGjhlJYKp0LLueVfAhjJB.jpg",
    price: "29,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 70,
    name: "Vở Dash Line lò xo kép bìa nhựa B5 200 trang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210621_26jBuur5EDmGwYhGI7ZbztUK.jpg",
    price: "93,000",
    status: "Còn hàng",
    describe:
      "Tập giấy note B5 30 tờ S42 màu retro S42 là sản phẩm tiện lợi giúp bạn ghi chú những điều quan trọng trong quá trình học tập và làm việc. Với thiết kế ghi chú caro, bạn có thể dễ dàng viết, vẽ hoặc tóm tắt nội dung một cách rõ ràng và hợp lý. Sản phẩm này không chỉ là vật dụng hỗ trợ công việc hiệu quả cho các nhân viên văn phòng hay sinh viên năng động trong quá trình học tập, nó còn được thiết kế theo phong cách Retro thu hút người tiêu dùng yêu thích vintage.",
    charac1: "- Kích thước B5",
    charac2: "- Số lượng 60 trang (30 tờ) ",
    charac3:
      "- Định lượng cao: Với định lượng 80gsm, sản phẩm có độ bền cao và không bị rách rách khi gấp hay xé.",
    charac4:
      "- Tạo thành sổ: Tập giấy note màu retro có thể được ghim lại để tạo thành các cuốn sổ bất kì theo ý muốn của bạn. Định lượng 100GSM phù hợp dùng bút bi, bút gel ",
  },
  {
    id: 71,
    name: "Bộ 24 bút đầu 2 brush + fine B07",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20210621_fKpisG4ViilwBxTxrz0yfQWo.jpg",
    price: "130,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
];
