const penGel = [
  {
    id: 95,
    name: "Bút gel tacotaco giảm mỏi tay mực nhanh khô",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240619_vEb0Lp99TR.jpeg",
    price: "13,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 96,
    name: "Bút gel đệm tay lớn 3 màu B131",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240520_QObhwjz4Di.png",
    price: "10,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 97,
    name: "Bút gel bấm Languo mực đen đệm tay dài",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240621_rxGg6oYQXw.jpeg",
    price: "15,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 98,
    name: "Set 6 bút highlight 2 đầu light color HI06",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240402_05cJd8EPDJ.png",
    price: "38,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 99,
    name: "Bút gel Deli lineflow nét mượt S60",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240701_QRqIu5DLR9.jpeg",
    price: "12,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 100,
    name: "Bút gel mực bấm Deli S128",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240314_0UKARBgXCj.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 101,
    name: "Bút gel Deli A575 mực đen",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240301_t7CK6nyUuz.png",
    price: "10,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 102,
    name: "Bút gel Deli nhiều màu A119",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_l4ZiX5Sc2K.jpeg",
    price: "6,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 103,
    name: "Hộp 5 bút đi nét Baoke B108",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_5fvM937SeZ.jpeg",
    price: "95,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 104,
    name: "Bút gel nét muột mực đen B105",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_XMQ8KlbTQY.jpeg",
    price: "5,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 105,
    name: "Combo 7 bút Moka bút gel, highlight nhiều loại",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240406_5svpWZYXZP.jpeg",
    price: "44,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 106,
    name: "Combo 7 bút Moka bút gel, highlight nhiều loại",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_g5gyP3XUYY.jpeg",
    price: "44,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
];
