const penHighlight = [
  {
    id: 84,
    name: "Bút highlight màu nhũ ánh kim khổ lớn <HL18></HL18>",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240427_nLKZtLoTrf.jpeg",
    price: "16,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 85,
    name: "Bút highlight thân trong HL14",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_7sm4msEz63.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 86,
    name: "Bộ 5 bút đánh dấu có nhũ ánh kim Shiny",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_FOhlwcMvsT.jpeg",
    price: "38,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 87,
    name: "Bộ 4 bút đánh dấu 2 đầu Good luck HL12",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_sJ32ZQry4u.jpeg",
    price: "31,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 89,
    name: "Set 6 bút highlight 2 đầu light color HI06",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240402_1PdXfZlPJO.png",
    price: "38,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 90,
    name: "Set 6 bút highlight 2 đầu light color HI06",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240402_05cJd8EPDJ.png",
    price: "38,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 91,
    name: "Bút highlight ngòi lăn kẻ đường họa tiết HI11",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_HyxgrCPnVs.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 92,
    name: "Bộ bút lông 20 màu Ret ro rửa được Fiber Pen",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_WINE3drYYT.jpeg",
    price: "68,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 93,
    name: "Bút dạ quang Thiên Long Pazto",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_qyQZUwGcmN.jpeg",
    price: "9,500",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 94,
    name: "Set 6 bút highlight dạ quang Taco Taco",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_qZq52jlc6d.jpeg",
    price: "80,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
];
