const productBook = [
  {
    id: 158,
    name: "Tập 30 tờ B5 2 cột viết công thức, ghi chú",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240410_sPyc7NLn4N.png",
    price: "20,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 159,
    name: "Tập 30 tờ giấy B5 học bài ghi chú cute",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240502_sb7iADJsg6.jpeg",
    price: "24,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 160,
    name: "Tập giấy B5 30 tờ caro/kẻ bầu trời",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240410_AzN2ToUZLD.png",
    price: "24,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 161,
    name: "Tập sổ tay note B5 30 tờ S42 màu retro",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240311_mH5HFkU8RZ.png",
    price: "19,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 162,
    name: "Tập 4 ly ngang khổ (156x205) mm 96tr",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240408_ARPFzKeZdi.jpeg",
    price: "10,800",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 163,
    name: "Tập 4 ô ly (2x2) mm khổ (156x205) mm 96tr",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240408_IpTDRIR8HS.jpeg",
    price: "10,800",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
];
