const productNoteBook = [
  {
    id: 40,
    name: "File bìa còng 2 đầu 10 chấu B5 Lite Binder",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240321_PnMEv0H7iM.jpeg",
    price: "16,000",
    status: "Còn hàng",
    describe:
      "Tập giấy note B5 30 tờ S42 màu retro S42 là sản phẩm tiện lợi giúp bạn ghi chú những điều quan trọng trong quá trình học tập và làm việc. Với thiết kế ghi chú caro, bạn có thể dễ dàng viết, vẽ hoặc tóm tắt nội dung một cách rõ ràng và hợp lý. Sản phẩm này không chỉ là vật dụng hỗ trợ công việc hiệu quả cho các nhân viên văn phòng hay sinh viên năng động trong quá trình học tập, nó còn được thiết kế theo phong cách Retro thu hút người tiêu dùng yêu thích vintage.",
    charac1: "- Kích thước B5",
    charac2: "- Số lượng 60 trang (30 tờ) ",
    charac3:
      "- Định lượng cao: Với định lượng 80gsm, sản phẩm có độ bền cao và không bị rách rách khi gấp hay xé.",
    charac4:
      "- Tạo thành sổ: Tập giấy note màu retro có thể được ghim lại để tạo thành các cuốn sổ bất kì theo ý muốn của bạn. Định lượng 100GSM phù hợp dùng bút bi, bút gel ",
  },
  {
    id: 41,
    name: "Sổ còng nhựa 2 đầu Panda S41",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240405_Rumvr0MMlZ.jpeg",
    price: "35,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 42,
    name: "Sổ tay kẹp còng nhựa bìa PP ombre S40",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240301_g9tc7K7T5z.png",
    price: "18,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 43,
    name: "Sổ tay A7 kẹp còng nhựa Movie Disney S37",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_2D8LvssIOz.jpeg",
    price: "16,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 44,
    name: "Sổ còng nhựa 2 đầu Mickey S36",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240125_AoKxEHGHRr.png",
    price: "30,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 44,
    name: "Sổ còng bìa vải khuy bấm vintage S30",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240314_47CGaydKnT.jpeg",
    price: "85,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 45,
    name: "Sổ còng học ghi nhớ từ mới B5 S28",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_TwBvgYI5XS.jpeg",
    price: "51,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 46,
    name: "Ruột bút mực đen B88R",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_G9iZyT7wlM.jpeg",
    price: "6,000",
    status: "Còn hàng",
    describe:
      "Bút mực gel thiết kế phong cách basic nhẹ nhàng, đơn giản, phù hợp với nhiều đối tượng sử dụng như học sinh, sinh viên, văn phòng....",
    charac1: "- Chất liêu: thân bút nhựa, ngòi thép không gỉ",
    charac2: "- Ngòi bút: nét 0.5mm. Bút và ruột đều là mực đen ",
    charac3: "- Bút gel có nắp trong suốt dễ cài",
    charac4: "- Chiều dài bút: 14cm ",
  },
  {
    id: 47,
    name: "Sổ còng 2 đầu B5 bìa trong suốt Never Give Up",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_pOY5JYeChS.jpeg",
    price: "49,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 48,
    name: "Ruột sổ kẹp còng caro 6x6 mm B5",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_8YxaCTsL5F.jpeg",
    price: "30,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 49,
    name: "Ruột sổ kẹp còng 5x5 mm B5",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_Fnm3ujv5o3.jpeg",
    price: "26,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
  {
    id: 50,
    name: "Sổ còng PAstel B5 mi giấy caro + kẻ ngang",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_1rvrsjrLqK.jpeg",
    price: "98,000",
    status: "Còn hàng",
    describe:
      "Ruột vở định lượng dày vừa phải với độ trắng cao nhưng không phản xạ ánh sáng, được in offset kẻ ngang với các chỉ thị toạ độ dọc ngang trên trang vở, dễ dàng xác định toạ độ dựng hình, tạo bảng, vẽ đồ thị; chất giấy gia keo không lem nhoè với hầu hết các loại mực, màu gốc nước. Kết cấu may dán gáy bền chắc không bong bìa, giấy khi sử dụng. Bìa thiết kế đơn giản với gam màu pastel được cán màng mờ, bảo vệ tốt bìa vở.",
    charac1: "- Định lượng 70 g/m²",
    charac2: "- Độ trắng 92% ISO ",
    charac3: "- Số trang 80 trang",
    charac4: "- Kích thước (175 x 250) mm ",
  },
];
