const productStudy = [
  {
    id: 152,
    name: "Đánh dấu sách nam châm K126",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240301_am9Ho7UUJA.png",
    price: "5,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 153,
    name: "Hộp đựng sách tài liệu để bàn lắp ráp K109",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20231128_HUl2TZRbow.jpeg",
    price: "40,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 154,
    name: "Cặp clear bag khóa zip để giấy A4 1 ngăn K117",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_oNKRwn9LEJ.jpeg",
    price: "55,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 155,
    name: "Thước kẻ 15cm họa tiết cute K125",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_Hzk22AKWEX.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 156,
    name: "Thanh kẹp gáy bìa nhựa Deli A4 K123",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20240313_xPleQEuwuJ.jpeg",
    price: "9,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
  {
    id: 157,
    name: "Giấy ghi chú trong suốt có màu NO25",
    src: "https://pos.nvncdn.com/7a6d8f-102734/ps/20220830_yZIkiBASm8FEqyxcvAPe7UZI.jpg",
    price: "15,000",
    status: "Còn hàng",
    describe:
      "Sổ tay lò xo kép sọc ngang Planner A5 Klong 200 trang được thiết kế để lên và thực hiện kế hoạch bản thân hoàn hảo nhất cho năm, tháng, tuần. Kết cấu lò xo kép ánh ngọc với bìa được thiết kế hiện đại, bồi dày (1200g/m2) tạo sự sang trọng, luôn mới. Ruột sổ được in offset rõ ràng, sắc nét, bố cục hợp lý trên giấy silky kem siêu mịn với định lượng 72,4g/m2, bắt mực.",
    charac1: "- Định lượng: 72,4 g/m2",
    charac2: "- Độ trắng: 76% ISO",
    charac3: "- Số trang: 200 trang",
    charac4: "- Kích thước: (148 x 210) mm",
  },
];
